applications:
  - name: postgrest
    instances: 1
    disk_quota: 256M
    memory: 128M
    timeout: 180
    docker:
      image: postgrest/postgrest:v10.1.2
    routes:
      - route: fac-staging-postgrest.app.cloud.gov
    env:
      PGRST_DB_URI: ((DB_URI))
      PGRST_DB_ANON_ROLE: anon

  - name: swagger-demo
    instances: 1
    disk_quota: 256M
    memory: 256M
    timeout: 20
    health-check-type: process
    docker:
      image: swaggerapi/swagger-ui
    routes:
      - route: fac-dev-swagger.app.cloud.gov
    env:
      API_URL: https://fac-dev-postgrest.app.cloud.gov
      SWAGGER_JSON_URL: https://fac-dev-postgrest.app.cloud.gov/
    port: 8080