CREATE OR REPLACE VIEW public.agency AS SELECT * FROM public.data_distro_agency;
CREATE OR REPLACE VIEW public.auditee AS SELECT * FROM public.data_distro_auditee;
CREATE OR REPLACE VIEW public.auditor AS SELECT * FROM public.data_distro_auditor;
CREATE OR REPLACE VIEW public.captext AS SELECT * FROM public.data_distro_captext;
CREATE OR REPLACE VIEW public.federal_award AS SELECT * FROM public.data_distro_federalaward;
CREATE OR REPLACE VIEW public.federal_award_findings AS SELECT * FROM public.data_distro_federalaward_findings;
CREATE OR REPLACE VIEW public.finding AS SELECT * FROM public.data_distro_finding;
CREATE OR REPLACE VIEW public.finding_text AS SELECT * FROM public.data_distro_findingtext;
CREATE OR REPLACE VIEW public.general AS SELECT * FROM public.data_distro_general;
CREATE OR REPLACE VIEW public.general_cap_text AS SELECT * FROM public.data_distro_general_cap_text;
CREATE OR REPLACE VIEW public.general_federal_awards AS SELECT * FROM public.data_distro_general_federal_awards;
CREATE OR REPLACE VIEW public.general_findings AS SELECT * FROM public.data_distro_general_findings;
CREATE OR REPLACE VIEW public.general_findings_text AS SELECT * FROM public.data_distro_general_findings_text;
CREATE OR REPLACE VIEW public.general_notes AS SELECT * FROM public.data_distro_general_notes;
CREATE OR REPLACE VIEW public.general_passthrough AS SELECT * FROM public.data_distro_general_passthrough;
CREATE OR REPLACE VIEW public.general_secondary_auditors AS SELECT * FROM public.data_distro_general_secondary_auditors;
CREATE OR REPLACE VIEW public.note AS SELECT * FROM public.data_distro_note;
CREATE OR REPLACE VIEW public.passthrough AS SELECT * FROM public.data_distro_passthrough;
CREATE OR REPLACE VIEW public.revision AS SELECT * FROM public.data_distro_revision;

GRANT SELECT ON public.agency TO anon;
GRANT SELECT ON public.auditee TO anon;
GRANT SELECT ON public.auditor TO anon;
GRANT SELECT ON public.captext TO anon;
GRANT SELECT ON public.federal_award TO anon;
GRANT SELECT ON public.federal_award_findings TO anon;
GRANT SELECT ON public.finding TO anon;
GRANT SELECT ON public.finding_text TO anon;
GRANT SELECT ON public.general TO anon;
GRANT SELECT ON public.general_cap_text TO anon;
GRANT SELECT ON public.general_federal_awards TO anon;
GRANT SELECT ON public.general_findings TO anon;
GRANT SELECT ON public.general_findings_text TO anon;
GRANT SELECT ON public.general_notes TO anon;
GRANT SELECT ON public.general_passthrough TO anon;
GRANT SELECT ON public.general_secondary_auditors TO anon;
GRANT SELECT ON public.note TO anon;
GRANT SELECT ON public.passthrough TO anon;
GRANT SELECT ON public.revision TO anon;

NOTIFY pgrst, 'reload schema';
